name: .NET

on: push

jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Build 
      working-directory: src      
      run: dotnet build --configuration Release
    - name: Test
      working-directory: src      
      run: dotnet test --configuration Release
    
  publishdocker:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./src --file Dockerfile --tag geodan/i3dm.export:latest
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish the Docker image
      run: docker push geodan/i3dm.export:latest
