name: .NET

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build 
      working-directory: src      
      run: dotnet build --configuration Release
    - name: Test
      working-directory: tests      
      run: dotnet test --configuration Release